Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,27 +18,27 @@ jobs:
               username: ${{ secrets.DOCKERHUB_USERNAME }}
               password: ${{ secrets.DOCKERHUB_PASSWORD }}  
 
-        - name: Setup Java JDK
-          uses: actions/setup-java@v3.14.1
-          with:
-            # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
-            java-version: '21'
-            distribution: 'oracle'
+        # - name: Setup Java JDK
+        #   uses: actions/setup-java@v3.14.1
+        #   with:
+        #     # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
+        #     java-version: '21'
+        #     distribution: 'oracle'
 
-        - name: Criar arquivo settings.xml # Evitar o problema: [DEBUG] Failed to decrypt password for server github: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: /home/runner/.m2/settings-security.xml (No such file or directory)
-          run: |
-            mkdir -p ~/.m2
-            cat <<EOF > ~/.m2/settings.xml
-            <settings>
-                <servers>
-                    <server>
-                        <id>github</id>
-                        <username>${{ secrets.GITHUB_ACTOR }}</username>
-                        <password>${{ secrets.GITHUB_TOKEN }}</password>
-                    </server>
-                </servers>
-            </settings>
-            EOF
+        # - name: Criar arquivo settings.xml # Evitar o problema: [DEBUG] Failed to decrypt password for server github: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: /home/runner/.m2/settings-security.xml (No such file or directory)
+        #   run: |
+        #     mkdir -p ~/.m2
+        #     cat <<EOF > ~/.m2/settings.xml
+        #     <settings>
+        #         <servers>
+        #             <server>
+        #                 <id>github</id>
+        #                 <username>${{ secrets.GITHUB_ACTOR }}</username>
+        #                 <password>${{ secrets.GITHUB_TOKEN }}</password>
+        #             </server>
+        #         </servers>
+        #     </settings>
+        #     EOF
 
         # - name: Eureka Naming Server
         #   working-directory: ./
@@ -77,16 +77,16 @@ jobs:
               exit 1
             fi
 
-        - name: MS Book
-          working-directory: ./components/ms_book-service
-          run: |
-            if [ -f "./pom.xml" ]; then
-              echo "Arquivo pom.xml do ms_book-service encontrado. Executando Maven..."
-              mvn clean package -DskipTests -X -e -f pom.xml
-            else
-              echo "Arquivo pom.xml do ms_book-service não encontrado. Parando build."
-              exit 1
-            fi
+        # - name: MS Book
+        #   working-directory: ./components/ms_book-service
+        #   run: |
+        #     if [ -f "./pom.xml" ]; then
+        #       echo "Arquivo pom.xml do ms_book-service encontrado. Executando Maven..."
+        #       mvn clean package -DskipTests -X -e -f pom.xml
+        #     else
+        #       echo "Arquivo pom.xml do ms_book-service não encontrado. Parando build."
+        #       exit 1
+        #     fi
 
         - name: Docker Compose Build
           working-directory: ./
